settings:
  title: 'Booqi Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
- id: backend-server-state
    name: frontend servers
    url: 'https://status-page.eidam.dev'
    method: GET
    expectStatus: 200
    linkable: false

  - id: frontend-server-state
    name: Frontend servers
    url: 'https://www.cloudflarestatus.com/'
    method: GET
    expectStatus: 200
    linkable: false

  - id: api-systems
    name: API systems
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: storage-systems
    name: Storage systems
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: anti-ddos-systems
    name: Anti DDoS systems
    url: 'https://blog.cloudflare.com/'
    method: GET
    expectStatus: 200

  - id: kiosk-systems
    name: Kiosk systems
    url: 'https://www.cloudflare.com/dns/'
    method: GET
    expectStatus: 200