settings:
  pageTitle: 'Status Page'
  title: '- Status Page'
  url: 'https://status.booqi.me'
  logo: logo.png
  daysInHistogram: 60
  collectResponseTimes: true

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Outage In Some Systems'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)'

monitors:
  - id: backend-server-state
    name: Backoffice servers
    description: 'This status reflects the current state of the servers handling requests from the backoffice.'
    url: 'https://museum.booqi.me/admin'
    method: GET
    expectStatus: 200
    linkable: false

  - id: frontend-server-state
    name: Shop servers
    description: 'This status reflects the current state of the servers handling requests from clients looking to purchase products.'
    url: 'https://museum.booqi.me'
    method: GET
    expectStatus: 200
    linkable: false

  - id: api-systems
    name: API servers
    description: 'This status reflects the current state of the servers handling requests from the API and Webhooks.'
    url: 'https://museum.booqi.me/api/client'
    method: GET
    expectStatus: 200
    linkable: false

  - id: storage-systems
    name: Storage servers
    description: 'This status provides an overview of all our storage systems, including images and reports.'
    url: 'https://cdn.booqi.app'
    method: GET
    expectStatus: 403
    linkable: false

  - id: anti-ddos-systems
    name: DDoS Mitigation systems
    description: 'This status reflects the current state of our DDoS mitigation systems and firewalls.'
    url: 'https://cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: false
